//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace XWiki.Rest.Model
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("xwiki", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class XWiki : LinkCollection
    {

        private string versionField;

        private Syntaxes syntaxesField;

        /// <remarks/>
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public Syntaxes syntaxes
        {
            get
            {
                return this.syntaxesField;
            }
            set
            {
                this.syntaxesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("syntaxes", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class Syntaxes : LinkCollection
    {

        private string[] syntaxField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("syntax")]
        public string[] syntax
        {
            get
            {
                return this.syntaxField;
            }
            set
            {
                this.syntaxField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Tag))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Class))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Property))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectSummary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Object))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Comment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HistorySummary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PageSummary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Page))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Space))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Wiki))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Syntaxes))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XWiki))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Translation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Translations))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    public partial class LinkCollection
    {

        private Link[] linkField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public Link[] link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    public partial class Link
    {

        private string hrefField;

        private string relField;

        private string typeField;

        private string hrefLangField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rel
        {
            get
            {
                return this.relField;
            }
            set
            {
                this.relField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hrefLang
        {
            get
            {
                return this.hrefLangField;
            }
            set
            {
                this.hrefLangField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    public partial class Attribute : LinkCollection
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    public partial class HistorySummary : LinkCollection
    {

        private string pageIdField;

        private string wikiField;

        private string spaceField;

        private string nameField;

        private string versionField;

        private int majorVersionField;

        private int minorVersionField;

        private System.DateTime modifiedField;

        private string modifierField;

        private string languageField;

        /// <remarks/>
        public string pageId
        {
            get
            {
                return this.pageIdField;
            }
            set
            {
                this.pageIdField = value;
            }
        }

        /// <remarks/>
        public string wiki
        {
            get
            {
                return this.wikiField;
            }
            set
            {
                this.wikiField = value;
            }
        }

        /// <remarks/>
        public string space
        {
            get
            {
                return this.spaceField;
            }
            set
            {
                this.spaceField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public int majorVersion
        {
            get
            {
                return this.majorVersionField;
            }
            set
            {
                this.majorVersionField = value;
            }
        }

        /// <remarks/>
        public int minorVersion
        {
            get
            {
                return this.minorVersionField;
            }
            set
            {
                this.minorVersionField = value;
            }
        }

        /// <remarks/>
        public System.DateTime modified
        {
            get
            {
                return this.modifiedField;
            }
            set
            {
                this.modifiedField = value;
            }
        }

        /// <remarks/>
        public string modifier
        {
            get
            {
                return this.modifierField;
            }
            set
            {
                this.modifierField = value;
            }
        }

        /// <remarks/>
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Page))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    public partial class PageSummary : LinkCollection
    {

        private string idField;

        private string fullNameField;

        private string wikiField;

        private string spaceField;

        private string nameField;

        private string titleField;

        private string parentField;

        private string parentIdField;

        private string xwikiRelativeUrlField;

        private string xwikiAbsoluteUrlField;

        private Translations translationsField;

        private string syntaxField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }

        /// <remarks/>
        public string wiki
        {
            get
            {
                return this.wikiField;
            }
            set
            {
                this.wikiField = value;
            }
        }

        /// <remarks/>
        public string space
        {
            get
            {
                return this.spaceField;
            }
            set
            {
                this.spaceField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }

        /// <remarks/>
        public string parentId
        {
            get
            {
                return this.parentIdField;
            }
            set
            {
                this.parentIdField = value;
            }
        }

        /// <remarks/>
        public string xwikiRelativeUrl
        {
            get
            {
                return this.xwikiRelativeUrlField;
            }
            set
            {
                this.xwikiRelativeUrlField = value;
            }
        }

        /// <remarks/>
        public string xwikiAbsoluteUrl
        {
            get
            {
                return this.xwikiAbsoluteUrlField;
            }
            set
            {
                this.xwikiAbsoluteUrlField = value;
            }
        }

        /// <remarks/>
        public Translations translations
        {
            get
            {
                return this.translationsField;
            }
            set
            {
                this.translationsField = value;
            }
        }

        /// <remarks/>
        public string syntax
        {
            get
            {
                return this.syntaxField;
            }
            set
            {
                this.syntaxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("translations", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class Translations : LinkCollection
    {

        private Translation[] translationField;

        private string defaultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("translation")]
        public Translation[] translation
        {
            get
            {
                return this.translationField;
            }
            set
            {
                this.translationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @default
        {
            get
            {
                return this.defaultField;
            }
            set
            {
                this.defaultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    public partial class Translation : LinkCollection
    {

        private string languageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class wikis : LinkCollection
    {

        private Wiki[] wikiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wiki")]
        public Wiki[] wiki
        {
            get
            {
                return this.wikiField;
            }
            set
            {
                this.wikiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("wiki", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class Wiki : LinkCollection
    {

        private string idField;

        private string nameField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class spaces : LinkCollection
    {

        private Space[] spaceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("space")]
        public Space[] space
        {
            get
            {
                return this.spaceField;
            }
            set
            {
                this.spaceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("space", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class Space : LinkCollection
    {

        private string idField;

        private string wikiField;

        private string nameField;

        private string homeField;

        private string xwikiRelativeUrlField;

        private string xwikiAbsoluteUrlField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string wiki
        {
            get
            {
                return this.wikiField;
            }
            set
            {
                this.wikiField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string home
        {
            get
            {
                return this.homeField;
            }
            set
            {
                this.homeField = value;
            }
        }

        /// <remarks/>
        public string xwikiRelativeUrl
        {
            get
            {
                return this.xwikiRelativeUrlField;
            }
            set
            {
                this.xwikiRelativeUrlField = value;
            }
        }

        /// <remarks/>
        public string xwikiAbsoluteUrl
        {
            get
            {
                return this.xwikiAbsoluteUrlField;
            }
            set
            {
                this.xwikiAbsoluteUrlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class pages : LinkCollection
    {

        private PageSummary[] pageSummaryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pageSummary")]
        public PageSummary[] pageSummary
        {
            get
            {
                return this.pageSummaryField;
            }
            set
            {
                this.pageSummaryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("page", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class Page : PageSummary
    {

        private string languageField;

        private string versionField;

        private int majorVersionField;

        private int minorVersionField;

        private System.DateTime createdField;

        private string creatorField;

        private System.DateTime modifiedField;

        private string modifierField;

        private string contentField;

        /// <remarks/>
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public int majorVersion
        {
            get
            {
                return this.majorVersionField;
            }
            set
            {
                this.majorVersionField = value;
            }
        }

        /// <remarks/>
        public int minorVersion
        {
            get
            {
                return this.minorVersionField;
            }
            set
            {
                this.minorVersionField = value;
            }
        }

        /// <remarks/>
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        public string creator
        {
            get
            {
                return this.creatorField;
            }
            set
            {
                this.creatorField = value;
            }
        }

        /// <remarks/>
        public System.DateTime modified
        {
            get
            {
                return this.modifiedField;
            }
            set
            {
                this.modifiedField = value;
            }
        }

        /// <remarks/>
        public string modifier
        {
            get
            {
                return this.modifierField;
            }
            set
            {
                this.modifierField = value;
            }
        }

        /// <remarks/>
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class history : LinkCollection
    {

        private HistorySummary[] historySummaryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("historySummary")]
        public HistorySummary[] historySummary
        {
            get
            {
                return this.historySummaryField;
            }
            set
            {
                this.historySummaryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class attachments : LinkCollection
    {

        private Attachment[] attachmentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachment")]
        public Attachment[] attachment
        {
            get
            {
                return this.attachmentField;
            }
            set
            {
                this.attachmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("attachment", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class Attachment : LinkCollection
    {

        private string idField;

        private string nameField;

        private int sizeField;

        private string versionField;

        private string pageIdField;

        private string pageVersionField;

        private string mimeTypeField;

        private string authorField;

        private System.DateTime dateField;

        private string xwikiRelativeUrlField;

        private string xwikiAbsoluteUrlField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public int size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string pageId
        {
            get
            {
                return this.pageIdField;
            }
            set
            {
                this.pageIdField = value;
            }
        }

        /// <remarks/>
        public string pageVersion
        {
            get
            {
                return this.pageVersionField;
            }
            set
            {
                this.pageVersionField = value;
            }
        }

        /// <remarks/>
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }

        /// <remarks/>
        public string author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        /// <remarks/>
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        public string xwikiRelativeUrl
        {
            get
            {
                return this.xwikiRelativeUrlField;
            }
            set
            {
                this.xwikiRelativeUrlField = value;
            }
        }

        /// <remarks/>
        public string xwikiAbsoluteUrl
        {
            get
            {
                return this.xwikiAbsoluteUrlField;
            }
            set
            {
                this.xwikiAbsoluteUrlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class comments : LinkCollection
    {

        private Comment[] commentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comment")]
        public Comment[] comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("comment", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class Comment : LinkCollection
    {

        private int idField;

        private string pageIdField;

        private string authorField;

        private System.DateTime dateField;

        private string highlightField;

        private string textField;

        /// <remarks/>
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string pageId
        {
            get
            {
                return this.pageIdField;
            }
            set
            {
                this.pageIdField = value;
            }
        }

        /// <remarks/>
        public string author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        /// <remarks/>
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        public string highlight
        {
            get
            {
                return this.highlightField;
            }
            set
            {
                this.highlightField = value;
            }
        }

        /// <remarks/>
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("property", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class Property : LinkCollection
    {

        private Attribute[] attributeField;

        private string valueField;

        private string nameField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attribute")]
        public Attribute[] attribute
        {
            get
            {
                return this.attributeField;
            }
            set
            {
                this.attributeField = value;
            }
        }

        /// <remarks/>
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("class", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class Class : LinkCollection
    {

        private string idField;

        private string nameField;

        private Property[] propertyField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public Property[] property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class classes : LinkCollection
    {

        private Class[] classField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("class")]
        public Class[] @class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class objects : LinkCollection
    {

        private ObjectSummary[] objectSummaryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objectSummary")]
        public ObjectSummary[] objectSummary
        {
            get
            {
                return this.objectSummaryField;
            }
            set
            {
                this.objectSummaryField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Object))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("objectSummary", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class ObjectSummary : LinkCollection
    {

        private string idField;

        private string guidField;

        private string pageIdField;

        private string wikiField;

        private string spaceField;

        private string pageNameField;

        private string classNameField;

        private int numberField;

        private string headlineField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        /// <remarks/>
        public string pageId
        {
            get
            {
                return this.pageIdField;
            }
            set
            {
                this.pageIdField = value;
            }
        }

        /// <remarks/>
        public string wiki
        {
            get
            {
                return this.wikiField;
            }
            set
            {
                this.wikiField = value;
            }
        }

        /// <remarks/>
        public string space
        {
            get
            {
                return this.spaceField;
            }
            set
            {
                this.spaceField = value;
            }
        }

        /// <remarks/>
        public string pageName
        {
            get
            {
                return this.pageNameField;
            }
            set
            {
                this.pageNameField = value;
            }
        }

        /// <remarks/>
        public string className
        {
            get
            {
                return this.classNameField;
            }
            set
            {
                this.classNameField = value;
            }
        }

        /// <remarks/>
        public int number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        public string headline
        {
            get
            {
                return this.headlineField;
            }
            set
            {
                this.headlineField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("object", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class Object : ObjectSummary
    {

        private Property[] propertyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public Property[] property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class properties : LinkCollection
    {

        private Property[] propertyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public Property[] property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("tag", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class Tag : LinkCollection
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class tags : LinkCollection
    {

        private Tag[] tagField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tag")]
        public Tag[] tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute("searchResult", Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class SearchResult : LinkCollection
    {

        private string typeField;

        private string idField;

        private string pageFullNameField;

        private string wikiField;

        private string spaceField;

        private string pageNameField;

        private string languageField;

        private string classNameField;

        private int objectNumberField;

        private bool objectNumberFieldSpecified;

        /// <remarks/>
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string pageFullName
        {
            get
            {
                return this.pageFullNameField;
            }
            set
            {
                this.pageFullNameField = value;
            }
        }

        /// <remarks/>
        public string wiki
        {
            get
            {
                return this.wikiField;
            }
            set
            {
                this.wikiField = value;
            }
        }

        /// <remarks/>
        public string space
        {
            get
            {
                return this.spaceField;
            }
            set
            {
                this.spaceField = value;
            }
        }

        /// <remarks/>
        public string pageName
        {
            get
            {
                return this.pageNameField;
            }
            set
            {
                this.pageNameField = value;
            }
        }

        /// <remarks/>
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        public string className
        {
            get
            {
                return this.classNameField;
            }
            set
            {
                this.classNameField = value;
            }
        }

        /// <remarks/>
        public int objectNumber
        {
            get
            {
                return this.objectNumberField;
            }
            set
            {
                this.objectNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool objectNumberSpecified
        {
            get
            {
                return this.objectNumberFieldSpecified;
            }
            set
            {
                this.objectNumberFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.xwiki.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.xwiki.org", IsNullable = false)]
    public partial class searchResults : LinkCollection
    {

        private SearchResult[] searchResultField;

        private string templateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("searchResult")]
        public SearchResult[] searchResult
        {
            get
            {
                return this.searchResultField;
            }
            set
            {
                this.searchResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string template
        {
            get
            {
                return this.templateField;
            }
            set
            {
                this.templateField = value;
            }
        }
    }
}
